"""Database package."""

from db.checkpoints import build_checkpoint_config, get_async_postgres_checkpointer
from db.repositories import (
    ApartmentDecision,
    MonitorTarget,
    get_active_search_criteria_record,
    get_apartment_feedback_map,
    get_monitor_settings_record,
    get_unseen_apartment_records,
    list_apartment_records_by_urls,
    list_due_monitor_targets,
    list_feedback_apartments,
    list_seen_apartments,
    mark_apartments_seen,
    replace_active_search_criteria,
    touch_monitor_last_checked_at,
    update_apartment_feedback_notion_sync,
    upsert_apartment_feedback,
    upsert_apartment_records,
    upsert_monitor_settings,
    upsert_telegram_user,
)

__all__ = [
    "ApartmentDecision",
    "MonitorTarget",
    "build_checkpoint_config",
    "get_active_search_criteria_record",
    "get_apartment_feedback_map",
    "get_async_postgres_checkpointer",
    "get_monitor_settings_record",
    "get_unseen_apartment_records",
    "list_apartment_records_by_urls",
    "list_due_monitor_targets",
    "list_feedback_apartments",
    "list_seen_apartments",
    "mark_apartments_seen",
    "replace_active_search_criteria",
    "touch_monitor_last_checked_at",
    "update_apartment_feedback_notion_sync",
    "upsert_apartment_feedback",
    "upsert_apartment_records",
    "upsert_monitor_settings",
    "upsert_telegram_user",
]
